query rockets {
  rockets {
    active
    boosters
    company
    cost_per_launch
    country
    description
    height {
      meters
      feet
    }
    id
    landing_legs {
      material
      number
    }
    mass {
      kg
      lb
    }
    name
    type
    wikipedia
    stages
    success_rate_pct
    first_flight
    diameter {
      feet
      meters
    }
  }
}
