query ships($limit: Int, $offset: Int) {
  ships(limit: $limit, offset: $offset) {
    image
    model
    name
    roles
    speed_kn
    status
    type
    url
    weight_kg
    weight_lbs
    year_built
    successful_landings
    home_port
    active
    attempted_landings
    class
    course_deg
    mmsi
  }
}
